/*
  日本語名から英語名を引くための対応表。
  PokeAPI から一度だけ取ってきて、ここに置いてある。

  PokeAPI の一覧は英語名しか返さないので、
  日本語で探すには、こちらで対応表を持つしかない。
  教材なので最初の 151 匹ぶん。
*/

export type PokemonIndexEntry = {
  id: number;
  /** 日本語名。検索はこれで行う */
  ja: string;
  /** PokeAPI に問い合わせるときの名前 */
  en: string;
};

export const pokemonIndex: PokemonIndexEntry[] = [
  { id: 1, ja: "フシギダネ", en: "bulbasaur" },
  { id: 2, ja: "フシギソウ", en: "ivysaur" },
  { id: 3, ja: "フシギバナ", en: "venusaur" },
  { id: 4, ja: "ヒトカゲ", en: "charmander" },
  { id: 5, ja: "リザード", en: "charmeleon" },
  { id: 6, ja: "リザードン", en: "charizard" },
  { id: 7, ja: "ゼニガメ", en: "squirtle" },
  { id: 8, ja: "カメール", en: "wartortle" },
  { id: 9, ja: "カメックス", en: "blastoise" },
  { id: 10, ja: "キャタピー", en: "caterpie" },
  { id: 11, ja: "トランセル", en: "metapod" },
  { id: 12, ja: "バタフリー", en: "butterfree" },
  { id: 13, ja: "ビードル", en: "weedle" },
  { id: 14, ja: "コクーン", en: "kakuna" },
  { id: 15, ja: "スピアー", en: "beedrill" },
  { id: 16, ja: "ポッポ", en: "pidgey" },
  { id: 17, ja: "ピジョン", en: "pidgeotto" },
  { id: 18, ja: "ピジョット", en: "pidgeot" },
  { id: 19, ja: "コラッタ", en: "rattata" },
  { id: 20, ja: "ラッタ", en: "raticate" },
  { id: 21, ja: "オニスズメ", en: "spearow" },
  { id: 22, ja: "オニドリル", en: "fearow" },
  { id: 23, ja: "アーボ", en: "ekans" },
  { id: 24, ja: "アーボック", en: "arbok" },
  { id: 25, ja: "ピカチュウ", en: "pikachu" },
  { id: 26, ja: "ライチュウ", en: "raichu" },
  { id: 27, ja: "サンド", en: "sandshrew" },
  { id: 28, ja: "サンドパン", en: "sandslash" },
  { id: 29, ja: "ニドラン♀", en: "nidoran-f" },
  { id: 30, ja: "ニドリーナ", en: "nidorina" },
  { id: 31, ja: "ニドクイン", en: "nidoqueen" },
  { id: 32, ja: "ニドラン♂", en: "nidoran-m" },
  { id: 33, ja: "ニドリーノ", en: "nidorino" },
  { id: 34, ja: "ニドキング", en: "nidoking" },
  { id: 35, ja: "ピッピ", en: "clefairy" },
  { id: 36, ja: "ピクシー", en: "clefable" },
  { id: 37, ja: "ロコン", en: "vulpix" },
  { id: 38, ja: "キュウコン", en: "ninetales" },
  { id: 39, ja: "プリン", en: "jigglypuff" },
  { id: 40, ja: "プクリン", en: "wigglytuff" },
  { id: 41, ja: "ズバット", en: "zubat" },
  { id: 42, ja: "ゴルバット", en: "golbat" },
  { id: 43, ja: "ナゾノクサ", en: "oddish" },
  { id: 44, ja: "クサイハナ", en: "gloom" },
  { id: 45, ja: "ラフレシア", en: "vileplume" },
  { id: 46, ja: "パラス", en: "paras" },
  { id: 47, ja: "パラセクト", en: "parasect" },
  { id: 48, ja: "コンパン", en: "venonat" },
  { id: 49, ja: "モルフォン", en: "venomoth" },
  { id: 50, ja: "ディグダ", en: "diglett" },
  { id: 51, ja: "ダグトリオ", en: "dugtrio" },
  { id: 52, ja: "ニャース", en: "meowth" },
  { id: 53, ja: "ペルシアン", en: "persian" },
  { id: 54, ja: "コダック", en: "psyduck" },
  { id: 55, ja: "ゴルダック", en: "golduck" },
  { id: 56, ja: "マンキー", en: "mankey" },
  { id: 57, ja: "オコリザル", en: "primeape" },
  { id: 58, ja: "ガーディ", en: "growlithe" },
  { id: 59, ja: "ウインディ", en: "arcanine" },
  { id: 60, ja: "ニョロモ", en: "poliwag" },
  { id: 61, ja: "ニョロゾ", en: "poliwhirl" },
  { id: 62, ja: "ニョロボン", en: "poliwrath" },
  { id: 63, ja: "ケーシィ", en: "abra" },
  { id: 64, ja: "ユンゲラー", en: "kadabra" },
  { id: 65, ja: "フーディン", en: "alakazam" },
  { id: 66, ja: "ワンリキー", en: "machop" },
  { id: 67, ja: "ゴーリキー", en: "machoke" },
  { id: 68, ja: "カイリキー", en: "machamp" },
  { id: 69, ja: "マダツボミ", en: "bellsprout" },
  { id: 70, ja: "ウツドン", en: "weepinbell" },
  { id: 71, ja: "ウツボット", en: "victreebel" },
  { id: 72, ja: "メノクラゲ", en: "tentacool" },
  { id: 73, ja: "ドククラゲ", en: "tentacruel" },
  { id: 74, ja: "イシツブテ", en: "geodude" },
  { id: 75, ja: "ゴローン", en: "graveler" },
  { id: 76, ja: "ゴローニャ", en: "golem" },
  { id: 77, ja: "ポニータ", en: "ponyta" },
  { id: 78, ja: "ギャロップ", en: "rapidash" },
  { id: 79, ja: "ヤドン", en: "slowpoke" },
  { id: 80, ja: "ヤドラン", en: "slowbro" },
  { id: 81, ja: "コイル", en: "magnemite" },
  { id: 82, ja: "レアコイル", en: "magneton" },
  { id: 83, ja: "カモネギ", en: "farfetchd" },
  { id: 84, ja: "ドードー", en: "doduo" },
  { id: 85, ja: "ドードリオ", en: "dodrio" },
  { id: 86, ja: "パウワウ", en: "seel" },
  { id: 87, ja: "ジュゴン", en: "dewgong" },
  { id: 88, ja: "ベトベター", en: "grimer" },
  { id: 89, ja: "ベトベトン", en: "muk" },
  { id: 90, ja: "シェルダー", en: "shellder" },
  { id: 91, ja: "パルシェン", en: "cloyster" },
  { id: 92, ja: "ゴース", en: "gastly" },
  { id: 93, ja: "ゴースト", en: "haunter" },
  { id: 94, ja: "ゲンガー", en: "gengar" },
  { id: 95, ja: "イワーク", en: "onix" },
  { id: 96, ja: "スリープ", en: "drowzee" },
  { id: 97, ja: "スリーパー", en: "hypno" },
  { id: 98, ja: "クラブ", en: "krabby" },
  { id: 99, ja: "キングラー", en: "kingler" },
  { id: 100, ja: "ビリリダマ", en: "voltorb" },
  { id: 101, ja: "マルマイン", en: "electrode" },
  { id: 102, ja: "タマタマ", en: "exeggcute" },
  { id: 103, ja: "ナッシー", en: "exeggutor" },
  { id: 104, ja: "カラカラ", en: "cubone" },
  { id: 105, ja: "ガラガラ", en: "marowak" },
  { id: 106, ja: "サワムラー", en: "hitmonlee" },
  { id: 107, ja: "エビワラー", en: "hitmonchan" },
  { id: 108, ja: "ベロリンガ", en: "lickitung" },
  { id: 109, ja: "ドガース", en: "koffing" },
  { id: 110, ja: "マタドガス", en: "weezing" },
  { id: 111, ja: "サイホーン", en: "rhyhorn" },
  { id: 112, ja: "サイドン", en: "rhydon" },
  { id: 113, ja: "ラッキー", en: "chansey" },
  { id: 114, ja: "モンジャラ", en: "tangela" },
  { id: 115, ja: "ガルーラ", en: "kangaskhan" },
  { id: 116, ja: "タッツー", en: "horsea" },
  { id: 117, ja: "シードラ", en: "seadra" },
  { id: 118, ja: "トサキント", en: "goldeen" },
  { id: 119, ja: "アズマオウ", en: "seaking" },
  { id: 120, ja: "ヒトデマン", en: "staryu" },
  { id: 121, ja: "スターミー", en: "starmie" },
  { id: 122, ja: "バリヤード", en: "mr-mime" },
  { id: 123, ja: "ストライク", en: "scyther" },
  { id: 124, ja: "ルージュラ", en: "jynx" },
  { id: 125, ja: "エレブー", en: "electabuzz" },
  { id: 126, ja: "ブーバー", en: "magmar" },
  { id: 127, ja: "カイロス", en: "pinsir" },
  { id: 128, ja: "ケンタロス", en: "tauros" },
  { id: 129, ja: "コイキング", en: "magikarp" },
  { id: 130, ja: "ギャラドス", en: "gyarados" },
  { id: 131, ja: "ラプラス", en: "lapras" },
  { id: 132, ja: "メタモン", en: "ditto" },
  { id: 133, ja: "イーブイ", en: "eevee" },
  { id: 134, ja: "シャワーズ", en: "vaporeon" },
  { id: 135, ja: "サンダース", en: "jolteon" },
  { id: 136, ja: "ブースター", en: "flareon" },
  { id: 137, ja: "ポリゴン", en: "porygon" },
  { id: 138, ja: "オムナイト", en: "omanyte" },
  { id: 139, ja: "オムスター", en: "omastar" },
  { id: 140, ja: "カブト", en: "kabuto" },
  { id: 141, ja: "カブトプス", en: "kabutops" },
  { id: 142, ja: "プテラ", en: "aerodactyl" },
  { id: 143, ja: "カビゴン", en: "snorlax" },
  { id: 144, ja: "フリーザー", en: "articuno" },
  { id: 145, ja: "サンダー", en: "zapdos" },
  { id: 146, ja: "ファイヤー", en: "moltres" },
  { id: 147, ja: "ミニリュウ", en: "dratini" },
  { id: 148, ja: "ハクリュー", en: "dragonair" },
  { id: 149, ja: "カイリュー", en: "dragonite" },
  { id: 150, ja: "ミュウツー", en: "mewtwo" },
  { id: 151, ja: "ミュウ", en: "mew" },
];
